id: A13EC3E61
title: Prayer to Karma Palden Khyentse
type: translation
pechas:
- I8B9ADD04
- I5040F9E9
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:46:54.773274
  last_modified_at: 2023-01-04 12:46:54.773294
  collections:
  - Karse Kongtrul Khyentse Özer
  - Works of Tibetan Masters
alignment_to_base:
  I8B9ADD04/7953: CBA8
  I5040F9E9/2BD6: CBA8
